version: '3.5'
services:
  postgres:
    container_name: tutorials_postgre
    image: postgres
    env_file:
      - .env
     
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres: