name: nuget-build-deploy

on:
  push:
    branches:
      - master
      - release/*
      - feature/*
  pull_request:
    branches: 
      - master
      - release/*
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: 6.0.x
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
          versionSpec: '5.x'
          
    - name: Check out Code 
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
          
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml  
    - name: Adjust NuGet Config Credentials
      run: |
        rm -f ./nuget.config
        mv nuget.ci.config nuget.config
        echo $(sed -e "s/\${USER}/${{ secrets.REGISTRY_USER }}/" -e "s@\${PAT}@${{  github.token }}@" nuget.config) >nuget.config
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build dotnet 
      run: dotnet build develop.sln --configuration release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore
            
    - name: Package nuget
      run: dotnet pack develop.sln --configuration release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./package/*.nupkg  --source "https://nuget.pkg.github.com/Geek-I-Am/index.json"  --api-key ${{ github.token }}